apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-public
  namespace: ingress
  annotations:
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: nginx-public
    spec:
      serviceAccountName: nginx-ingress-serviceaccount
      containers:
      - image:  quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.18.0 
        name: nginx
        imagePullPolicy: Always
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        ports:
        - containerPort: 80
        - containerPort: 443
        args:
        - /nginx-ingress-controller
        - --default-backend-service=$(POD_NAMESPACE)/default-http-backend
        - --configmap=$(POD_NAMESPACE)/nginx
        - --default-ssl-certificate=$(POD_NAMESPACE)/default-tls

