apiVersion: v1
kind: Pod
metadata:
  name: foobar
  namespace: jer-test
spec:
  containers:
  - image: "ubuntu:18.04"
    command:
      - sleep
      - "14400"
    name: foobar
  restartPolicy: Always
